# Configuration for cargo-deny
# https://embarkstudios.github.io/cargo-deny/

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
skip = []
skip-tree = []

# Deny specific crates
deny = [
    # Crates with known security issues
    { name = "openssl", reason = "Use rustls instead" },
    { name = "pcre2", reason = "Use regex instead" },
    
    # Deprecated crates
    { name = "failure", reason = "Use thiserror/anyhow instead" },
    { name = "lazy_static", reason = "Use once_cell instead" },
]

[licenses]
version = 2
confidence-threshold = 0.8
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "Zlib",
    "BSL-1.0",
]

deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-3.0",
    "LGPL-2.1",
    "LGPL-3.0",
]

copyleft = "deny"
default = "deny"
unlicensed = "deny"

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = []