apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ares-csf-data
  labels:
    app: ares-csf
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd