apiVersion: v1
kind: ServiceAccount
metadata:
  name: ares-csf
  labels:
    app: ares-csf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ares-csf
  labels:
    app: ares-csf
rules:
# Allow reading pods for peer discovery
- apiGroups: [""]
  resources: ["pods", "endpoints"]
  verbs: ["get", "list", "watch"]
# Allow reading services for peer discovery
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
# Allow reading configmaps for dynamic configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Allow creating events for auditing
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ares-csf
  labels:
    app: ares-csf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ares-csf
subjects:
- kind: ServiceAccount
  name: ares-csf